### ISSUE TITLE
minor error and suggestions

### ISSUE THREAD

**Issue by grseidel** [No13/ApsYc600-Pythonlib#1]
Hi,
first of all great implementation. Of all the solutions for the YC600 based on Koenkk issue page I find this the most suitable. I got it up and running in no time...

First the minor error: in the aps_yc600.py the energy_panel readings for 1 and 2 are exchanged. Easy fix.

Some small suggestions for your README.md file:
- the pairing.py is missing an 'import time'
- pairing and polling could be ended with 'GPIO.cleanup()' to avoid a warning the second time around
- when you mention the 'pins for communication' you should add the RPi side GPIO 14,15

Last two ideas which I think would benefit this implementation:
1) apparently there are implementations which gather the AC_energy - I have not found the register for this in the Koenkk issue page though
2) your calculation of power is correct as a snapshot in time. For daily tracking the average power since the last reading would be more useful, i.e. P [W] = (e(n) - e(n-1)) / (t(n)-t(n-1)

I will work on this ideas myself, maybe we can collaborate?
Rgds.
GES

**Comment by No13** [comment]
Thank you for your interest :) 
Improvements are always welcome!

I will look into the swapping of the panels and the finetuning of the README.

About your suggestions; AC_Energy is much wanted from my end too ;) If you ever track down the registers please inform me!

About the power 'snapshot'. I think both values would be interesting for me, so I will try to add these...

Contributions in the form of diffs / pull requests are always welcome ;)

**Comment by No13** [comment]
This is my current setup as of yesterday
![image](https://user-images.githubusercontent.com/1051219/151344245-23f8ef42-688c-4bb2-ba32-fa6fcdb4cfe6.png)

**Comment by grseidel** [comment]
That looks very professional, is the PCB custom made?
My hardware is still 'on the fly' with a laptop power supply driving the YC600...
To give you an impression of the direction I plan to go here is the dashboard I designed to track my PV-system once it is installed.
![image](https://user-images.githubusercontent.com/47289599/151511124-5cb50680-5806-402b-9176-236a88c02696.png)

**Comment by grseidel** [comment]
I add 3 python scripts into my fork:
- polling & pairing with my minor suggestions
- protocolling which continuously writes the values in an InfluxDB and calculates power based in energy/time

Feel free to take a look if this is of any use for the main fork...

**Comment by grseidel** [comment]
As to ac_energy: after a code inspection i concluded there is no such counter. Reconsidering how MPP-trackers work that is probable fine...
