### ISSUE TITLE
Question: example script to show basic usage of aps_yc600.py available?

### ISSUE THREAD

**Issue by mi-hol** [No13/ApsYc600-Pythonlib#3]
@No13 @grseidel 

I have DS3 and QT2 inverters and would like to add specifically the QT2

Currently I query my connected ECU-B from Windows PowerShell using a modified py script from a GH post that seems to stem originally from  https://github.com/Doudou14/Domoticz-apsystems_ecu/blob/main/ECU/APSystemsECU.py (example at bottom)

Next planned activity is to use an ESP32 to connect to inverters directly.

Now both programming an ESP32 and python are new skills to master.
Looking at Demo-ESP32 I found https://github.com/No13/ApsYc600-Pythonlib/blob/master/Demo-ESP32/poll.py but the code is a bit overwhelming.

Would you have a hint which example script(s) I should use to understand basic usage of aps_yc600.py?

Example:

```
."C:\Program Files\Python312\python.exe" .\ECUquery.py
{
  "timestamp": "2024-09-12 16:50:37",
  "inverter_qty": 1,
  "inverters": [
    {
      "uid": "702000******",
      "online": true,
      "unknown": "01",
      "frequency": 49.9,
      "temperature": 30,
      "model": "DS3",
      "channel_qty": 2,
      "power": [
        86,
        90
      ],
      "voltage": [
        239,
        239
      ]
    }
  ],
  "total_power": 176
}
```

**Comment by grseidel** [comment]
The requested example script is in the main page (polling.py).
Current implementation is for YC600 only.
I extended and tested for QS1 (but have not yet updated my fork).
Apparently patience4711 has added DS3 in his implementation.
I have no idea whether QT2 zigbee protocol has already been reverse engineered...

**Comment by mi-hol** [comment]
Thanks for your fast answer

> The requested example script is in the main page (polling.py).

I'm sorry but fail to see polling.py in this repo's main directory and GH search has no search hits. 
Maybe you could copy the URL here?
![image](https://github.com/user-attachments/assets/24d706b2-7e0e-4584-b1ed-ed6a400f1a0a)

> I extended and tested for QS1 (but have not yet updated my fork).

Would you mind to update your fork?
I assume QS1 and QT2 are similar because the later is the successor.

**Comment by grseidel** [comment]
Read the README.md!
I have updated my repository, but my aps_yc600.py is clearly more cluttered and therefore perhaps harder to understand than the original. I do some logging with it and had further data printed to understand the communication, which are currently commented out.

**Comment by mi-hol** [comment]
> Read the README.md!

Right, the basic example seems to be the section https://github.com/No13/ApsYc600-Pythonlib?tab=readme-ov-file#polling-inverter

**Comment by mi-hol** [comment]
Published my learnings via ECU_B.py in https://github.com/mi-hol/readAPSystemsECU
